# Generated by Django 5.0.1 on 2024-02-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slog',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slog',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
