# Generated by Django 5.0.1 on 2024-02-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_color_size_product_status_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slog',
        ),
    ]
