# Generated by Django 5.0.1 on 2024-02-14 14:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_product_slog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
