# Generated by Django 5.0.1 on 2024-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_product_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slog',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
