# Generated by Django 5.0.1 on 2024-02-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=None, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='home.comment'),
        ),
    ]
