# Generated by Django 5.0.1 on 2024-02-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
