# Generated by Django 5.0.1 on 2024-02-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_content_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_reply',
        ),
    ]
