# Generated by Django 5.0.1 on 2024-03-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_product_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_favorite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
